package Vista;

import Vista.JP_Preguntas;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Bus.Coneccion;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author e_raz
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private JPanel JP_Preguntas1;
    private Image background;
    private JLabel jlabel1;
    private JPanel JPO_Estadisticas;    
    private  BufferedImage BI_IniciarTest,BI_IniciarTest_Seleccion,BI_Carrera,BI_Estadisticas,BI_Estadisticas_Seleccion;
    private JP_Preguntas JPO_Preguntas;
    private Coneccion con;
    public Ventana(Coneccion con) throws IOException {
        this.con=con;       
        initComponents();     
        JP_Principal.setBounds(0,0,1080,720);
        JP_Principal.setVisible(true);
         
    }
    public JPanel getPanelPrincipal(){
        return this.JP_Principal;
    }   
    public JFrame getFrame(){
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JP_Principal.setMinimumSize(new java.awt.Dimension(1000, 700));
        JP_Principal.setPreferredSize(new java.awt.Dimension(1080, 720));
        JP_Principal.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel JP_Principal;
    // End of variables declaration//GEN-END:variables
}
